version: "3.9"
services:
  admin:
    build:
      context: ./admin
    ports:
      - "8888:8000" # Map container port 3000 to host port 3001
    volumes:
      - ./admin
      - /node_modules
    environment:
      - NODE_ENV=development

  company:
    build:
      context: ./company
    ports:
      - "8881:8881" # Map container port 3000 to host port 3002
    volumes:
      - ./company
      - /node_modules
    environment:
      - NODE_ENV=development

  student:
    build:
      context: ./student
    ports:
      - "8882:8882" # Map container port 3000 to host port 3003
    volumes:
      - ./student
      - /node_modules
    environment:
      - NODE_ENV=development

  university:
    build:
      context: ./university
    ports:
      - "8883:8883" # Map container port 3000 to host port 3003
    volumes:
      - ./university
      - /node_modules
    environment:
      - NODE_ENV=development
